language: ruby

rvm:
  - "2.6.6"
  - "2.7.1"
  - "ruby-head"

matrix:
  allow_failures:
    - rvm: "ruby-head"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y flac lame sox

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"

script:
  - bundle exec rspec

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
