# Your Redacted username and password
username: your_username
password: your_password

# Many FLAC torrents on Redacted marked as 16-bit are actually 24-bit, mostly
# coming from Bandcamp, which does not make a distinction on their download
# page. If this setting is set to true, redacted_better will attempt to modify
# the torrent, and get another regular FLAC upload at the same time. This will
# only occur on torrents which you have permission to edit. Users belonging to
# the Elite class or higher have edit permissions for all torrents. Otherwise,
# you are only allowed to edit torrents you have uploaded yourself.
fix_mislabeled_24bit: true

# File directories
directories:
  download: /media/data/torrents/music
  output: /media/data/torrents/redacted_upload
  torrents: /media/data/torrents/redacted_upload/torrent_files

# Software executables
executables:
  flac: # /usr/local/bin/flac
  sox: # /usr/local/bin/sox
  lame: # /usr/local/bin/lame
